import React from "react"
import { Button } from "../src/ui/primitives/Button/Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/A71qEYl40nE9sMd23vdRw1/SDS-Code-Connect-Tutorial-(Chad)?node-id=9762%3A426",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
      }),
      emphasis: figma.enum("Variant", {
        Neutral: "neutral",
        Subtle: "subtle",
      }),

      "IconStart": figma.boolean('Has Icon Start', {
        true: figma.instance('Icon Start'),
        false: undefined
      }),
      "IconEnd": figma.boolean('Has Icon End', {
        true: figma.instance('Icon End'),
        false: undefined
      }),
      "label": figma.string('Label'),
      isDisabled: figma.enum('State', {
        "Disabled": true
      })
    },
    example: ({size, emphasis, IconStart, IconEnd, label, isDisabled}) => 
    <Button onPress={() => {}}
     size={size}
     emphasis={emphasis}
     isDisabled={isDisabled}
     >
    {IconStart}
    {label}
    {IconEnd}
    </Button>,
  },
)
