import React from "react"
import { IconButton } from "../src/ui/primitives/IconButton/IconButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/A71qEYl40nE9sMd23vdRw1/SDS-Code-Connect-Tutorial-(Chad)?node-id=11%3A11508",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('Icon'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Disabled": "disabled"
      // })
    },
    example: (props) => (
      <IconButton
        variant={props.variant}
        size={props.size}
        aria-label={/* TODO */}
      />
    ),
  },
)
